### ISSUE TITLE
Cannot start the EXe (missing DLL's)

### ISSUE THREAD

**Issue by pantaluna** [joembedded/SPS30_particle_sensor#1]
I have downloaded the repo and when starting the sps30_win.exe then various Windows10 system errors pop up and then the app aborts. These are the dialog box errors:
- The code execution cannot proceed because BORLNDMM.DLL was not found.
- The code execution cannot proceed because vcl250.bpl was not found.
- The code execution cannot proceed because rtl250.bpl was not found.
- The code execution cannot proceed because CC32250MT.DLL was not found.

What should I do now?

Thanks for making the tool. It is great for 1st time users of the SPS30.

**Comment by spirit1** [comment]
+1 :)

**Comment by joembedded** [comment]
Thanks for the info. I added the missing dlls and bpls.

**Comment by spirit1** [comment]
Thank you, JoE! :)
